/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChallengeTask = IDL.Record({ 'day' : IDL.Nat, 'task' : IDL.Text });
export const WellnessChallenge = IDL.Record({
  'id' : IDL.Text,
  'tasks' : IDL.Vec(ChallengeTask),
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const WellnessPreferences = IDL.Record({
  'activityLevel' : IDL.Text,
  'ageRange' : IDL.Text,
  'wellnessGoals' : IDL.Vec(IDL.Text),
  'focusAreas' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'lastUpdated' : Time,
  'preferences' : WellnessPreferences,
});
export const ChallengeProgress = IDL.Record({
  'completedTasks' : IDL.Vec(IDL.Nat),
  'joinedAt' : Time,
  'challengeId' : IDL.Text,
});
export const WellnessKit = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'assetsUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'completeTask' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getChallenge' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WellnessChallenge)],
      ['query'],
    ),
  'getChallenges' : IDL.Func([], [IDL.Vec(WellnessChallenge)], ['query']),
  'getPreferences' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Vec(ChallengeProgress)], ['query']),
  'getWellnessKits' : IDL.Func([], [IDL.Vec(WellnessKit)], ['query']),
  'joinChallenge' : IDL.Func([IDL.Text], [], []),
  'leaveChallenge' : IDL.Func([IDL.Text], [], []),
  'savePreferences' : IDL.Func([WellnessPreferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChallengeTask = IDL.Record({ 'day' : IDL.Nat, 'task' : IDL.Text });
  const WellnessChallenge = IDL.Record({
    'id' : IDL.Text,
    'tasks' : IDL.Vec(ChallengeTask),
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const WellnessPreferences = IDL.Record({
    'activityLevel' : IDL.Text,
    'ageRange' : IDL.Text,
    'wellnessGoals' : IDL.Vec(IDL.Text),
    'focusAreas' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'lastUpdated' : Time,
    'preferences' : WellnessPreferences,
  });
  const ChallengeProgress = IDL.Record({
    'completedTasks' : IDL.Vec(IDL.Nat),
    'joinedAt' : Time,
    'challengeId' : IDL.Text,
  });
  const WellnessKit = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'assetsUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'completeTask' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WellnessChallenge)],
        ['query'],
      ),
    'getChallenges' : IDL.Func([], [IDL.Vec(WellnessChallenge)], ['query']),
    'getPreferences' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Vec(ChallengeProgress)], ['query']),
    'getWellnessKits' : IDL.Func([], [IDL.Vec(WellnessKit)], ['query']),
    'joinChallenge' : IDL.Func([IDL.Text], [], []),
    'leaveChallenge' : IDL.Func([IDL.Text], [], []),
    'savePreferences' : IDL.Func([WellnessPreferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };