/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChallengeProgress {
  'completedTasks' : Array<bigint>,
  'joinedAt' : Time,
  'challengeId' : string,
}
export interface ChallengeTask { 'day' : bigint, 'task' : string }
export type Time = bigint;
export interface UserProfile {
  'lastUpdated' : Time,
  'preferences' : WellnessPreferences,
}
export interface WellnessChallenge {
  'id' : string,
  'tasks' : Array<ChallengeTask>,
  'title' : string,
  'duration' : bigint,
  'description' : string,
}
export interface WellnessKit {
  'id' : string,
  'title' : string,
  'description' : string,
  'assetsUrl' : string,
}
export interface WellnessPreferences {
  'activityLevel' : string,
  'ageRange' : string,
  'wellnessGoals' : Array<string>,
  'focusAreas' : Array<string>,
}
export interface _SERVICE {
  'completeTask' : ActorMethod<[string, bigint], undefined>,
  'getChallenge' : ActorMethod<[string], [] | [WellnessChallenge]>,
  'getChallenges' : ActorMethod<[], Array<WellnessChallenge>>,
  'getPreferences' : ActorMethod<[], [] | [UserProfile]>,
  'getProgress' : ActorMethod<[], Array<ChallengeProgress>>,
  'getWellnessKits' : ActorMethod<[], Array<WellnessKit>>,
  'joinChallenge' : ActorMethod<[string], undefined>,
  'leaveChallenge' : ActorMethod<[string], undefined>,
  'savePreferences' : ActorMethod<[WellnessPreferences], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];