/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WellnessKit {
    id: string;
    title: string;
    description: string;
    assetsUrl: string;
}
export interface ChallengeProgress {
    completedTasks: Array<bigint>;
    joinedAt: Time;
    challengeId: string;
}
export type Time = bigint;
export interface ChallengeTask {
    day: bigint;
    task: string;
}
export interface WellnessChallenge {
    id: string;
    tasks: Array<ChallengeTask>;
    title: string;
    duration: bigint;
    description: string;
}
export interface UserProfile {
    lastUpdated: Time;
    preferences: WellnessPreferences;
}
export interface WellnessPreferences {
    activityLevel: string;
    ageRange: string;
    wellnessGoals: Array<string>;
    focusAreas: Array<string>;
}
export interface backendInterface {
    completeTask(challengeId: string, day: bigint): Promise<void>;
    getChallenge(id: string): Promise<WellnessChallenge | null>;
    getChallenges(): Promise<Array<WellnessChallenge>>;
    getPreferences(): Promise<UserProfile | null>;
    getProgress(): Promise<Array<ChallengeProgress>>;
    getWellnessKits(): Promise<Array<WellnessKit>>;
    joinChallenge(challengeId: string): Promise<void>;
    leaveChallenge(challengeId: string): Promise<void>;
    savePreferences(preferences: WellnessPreferences): Promise<void>;
}
import type { UserProfile as _UserProfile, WellnessChallenge as _WellnessChallenge } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeTask(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0, arg1);
            return result;
        }
    }
    async getChallenge(arg0: string): Promise<WellnessChallenge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenge(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenge(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallenges(): Promise<Array<WellnessChallenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenges();
            return result;
        }
    }
    async getPreferences(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<Array<ChallengeProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return result;
        }
    }
    async getWellnessKits(): Promise<Array<WellnessKit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWellnessKits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWellnessKits();
            return result;
        }
    }
    async joinChallenge(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinChallenge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinChallenge(arg0);
            return result;
        }
    }
    async leaveChallenge(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveChallenge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveChallenge(arg0);
            return result;
        }
    }
    async savePreferences(arg0: WellnessPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePreferences(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WellnessChallenge]): WellnessChallenge | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
